[project]
name = "Colmedicos"
version = "0.1.0"
description = "Utilidades de análisis y gráficos"
requires-python = ">=3.10"

[tool.black]
line-length = 100

[tool.ruff]
line-length = 100
select = ["E","F","I"]  # errores, flake8, import order

[tool.isort]
profile = "black"
src_paths = ["src"]

